        server:
          port: 8080

        spring:
          datasource:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/nep?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
            username: ${NEP_DB_USERNAME:root}
            password: ${NEP_DB_PASSWORD:}
          mvc:
            pathmatch:
              matching-strategy: ant_path_matcher

        mybatis-plus:
          configuration:
            map-underscore-to-camel-case: true
          mapper-locations: classpath*:mapper/*.xml
